@echo off
REM ****************************************************************************
REM Vivado (TM) v2026.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 21 14:24:19 -0600 2026
REM SW Build 6511674 on Tue Jun 16 11:02:23 MDT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim tb_adder_instantiation_behav -key {Behavioral:sim_1:Functional:tb_adder_instantiation} -tclbatch tb_adder_instantiation.tcl -log simulate.log"
call xsim  tb_adder_instantiation_behav -key {Behavioral:sim_1:Functional:tb_adder_instantiation} -tclbatch tb_adder_instantiation.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
